"""initial migrate

Revision ID: 6864cb610277
Revises: 
Create Date: 2026-03-12 01:33:58.721378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6864cb610277'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caixa_config', schema=None) as batch_op:
        batch_op.alter_column('saldo_inicial',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('cor',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'#6c63ff'::text"))
        batch_op.drop_constraint(batch_op.f('categorias_nome_usuario_id_key'), type_='unique')
        batch_op.create_unique_constraint('uq_categoria_nome_usuario', ['nome', 'usuario_id'])

    with op.batch_alter_table('gastos', schema=None) as batch_op:
        batch_op.alter_column('descricao',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('valor',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('data',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('anotacao',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("''::text"))
        batch_op.alter_column('criado_em',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_gastos_usuario_data'))

    with op.batch_alter_table('investimentos', schema=None) as batch_op:
        batch_op.alter_column('descricao',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('valor',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('tipo',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'Outro'::text"))
        batch_op.alter_column('data',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('anotacao',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("''::text"))
        batch_op.alter_column('criado_em',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_investimentos_user_data'))

    with op.batch_alter_table('receitas', schema=None) as batch_op:
        batch_op.alter_column('descricao',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('valor',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('data',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('anotacao',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("''::text"))
        batch_op.alter_column('criado_em',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_receitas_usuario_data'))

    # --- usuarios: migração segura com dados existentes ---
    # 1) Adiciona coluna username como NULLABLE primeiro
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(), nullable=True))

    # 2) Copia email → username para linhas existentes
    op.execute("UPDATE usuarios SET username = email WHERE username IS NULL")

    # 3) Agora aplica NOT NULL e ajusta constraints/colunas
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('username', nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('usuarios_username_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('reset_token_expires')
        batch_op.drop_column('reset_token')
        batch_op.drop_column('token')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('token', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reset_token', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reset_token_expires', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('usuarios_username_key'), ['email'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('username')

    with op.batch_alter_table('receitas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_receitas_usuario_data'), ['usuario_id', 'data'], unique=False)
        batch_op.alter_column('criado_em',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('anotacao',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("''::text"))
        batch_op.alter_column('data',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('valor',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('descricao',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('investimentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_investimentos_user_data'), ['usuario_id', 'data'], unique=False)
        batch_op.alter_column('criado_em',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('anotacao',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("''::text"))
        batch_op.alter_column('data',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('tipo',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'Outro'::text"))
        batch_op.alter_column('valor',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('descricao',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('gastos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_gastos_usuario_data'), ['usuario_id', 'data'], unique=False)
        batch_op.alter_column('criado_em',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('anotacao',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("''::text"))
        batch_op.alter_column('data',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('valor',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('descricao',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_constraint('uq_categoria_nome_usuario', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('categorias_nome_usuario_id_key'), ['nome', 'usuario_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('cor',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'#6c63ff'::text"))
        batch_op.alter_column('nome',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('caixa_config', schema=None) as batch_op:
        batch_op.alter_column('saldo_inicial',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###
